### PR TITLE
Explore watersurfaces version 'watersurfaces_v1.2'

### PR DESCRIPTION
**Pull request by florisvdh**
This was a long overdue task: version 1.2 was uploaded at Zenodo at the end of 2022. The first part of this exploration was already done in March this year.

The findings will be followed up by an update of `read_watersurfaces()` in {n2khab}.

If anyone's interested to review the updates of this exploration relative to version 1.1 as made by @cecileherr, please shout. Beside usual checks and resulting structural differences with version 1.1, smaller additions were made here and there.

- Compiled document for version 1.2 (by me): [watersurfaces.html.zip](https://github.com/inbo/n2khab-preprocessing/files/13335322/watersurfaces.html.zip)
- Compiled document for version 1.1 (by Cécile): [watersurfaces_v1_1_20210308.html.zip](https://github.com/inbo/n2khab-preprocessing/files/13335336/watersurfaces_v1_1_20210308.html.zip)

### CODE REVIEW

**Comment by ToonHub** [comment]
I will have a look.

**Comment by florisvdh** [comment]
I've added the compiled documents for versions 1.2 and 1.1 in the top post, had forgotten to do that.

**Comment by ToonHub** [comment]
Nice work! It's a pity they didn't ask you to check the data source before it was published. 

I am not sure what to do with the invalid geometries. But it might be best to only correct them in derived products.

**Comment by florisvdh** [comment]
> it might be best to only correct them in derived products.

Yes, I also think that makes most sense.

Thanks for reviewing.

**Pull request merged**
