### PR TITLE
Generate raster runif

### PR DESCRIPTION
**Pull request by ToonHub**
Some additional corrections based on the comments of @florisvdh

### CODE REVIEW

**Comment by ToonHub** [comment]
[generating_raster_runif.zip](https://github.com/inbo/n2khab-preprocessing/files/6384487/generating_raster_runif.zip)

**Review by florisvdh — APPROVED** [review]
Thanks for these updates @ToonHub :+1:. I've suggested some more in #57 (a PR that goes to this branch), while trying to reproduce the result.

**Comment by ToonHub** [comment]
@florisvdh : can you check if you can reproduce the result now. The new xxh64 hash is 384aceba96c12f60 (I have not changed it yet in the googlesheet)

I rounded the runif values to 5 digits. I also noticed that raster::mask in some runs rounded the runif values to 0 and 1. In other runs, the rounding was not performed. Strange... I avoided this problem by multiplying the runif values bij 100000 before masking and the result deviding them by 100000.  

The check of CRS gives a FALSE. I guess this has to be solved in the read_raster_runif function?

**Comment by florisvdh** [comment]
No, I get `d8ce6aa300a65209` :thinking:

Thank you for correcting the `writeRaster()` implementation.

Regarding CRS, we can successfully check it (cf. attached html in #58) and in my case it gave `TRUE` before, but it may have to do with `gdalUtils`, or perhaps with different versions between multiple PROJ installations on Windows (included in the respective packages). Since #57 the latter can be checked in the environment appendix of the html (`sf` and `rgdal` now appear separately for PROJ/GDAL versions). In #58 I propose a way to not use `gdalUtils` but `rgdal` to check the WKT independently of `raster`. Can you try that one? Meanwhile, an issue has been posted about WKT string change in `raster` at https://github.com/rspatial/raster/issues/199.

In pursuit of the checksum, I made two extra (temporary) branches (on top of #58):

- not setting `option(digits)`: branch `generate_raster_runif_fv_nodigits` - see fc3a2ed: gives `d8ce6aa300a65209` again
- not setting `option(digits)` and not doing the multiplying in 56ed5b7: branch `generate_raster_runif_fv_nodigits_nomultiply` - see 2752bf9: gives `9aec406e1cef4fcd`. That is the same result that I got when I ran it before your change in 56ed5b7, i.e. with `option(digits = 15)` and without multiplying/dividing.

So it seems that `option(digits)` has no effect at all - I think it just affects printing in R.

Multiplying does have an effect, but the cause of current non-reproducibility between platforms may be in `set.seed()` or `runif()`, or perhaps caused by different GDAL GeoTIFF driver versions, who knows. You're free to pursue it further :wink:, I'm available to do further runs. 

Actually we should all work on one machine in a docker environment to get strict reproducibility; cross-machine reproducibility remains a challenge when external tools are used (like drivers and random number generators); `renv` can only take care of the R side.

**Comment by florisvdh** [comment]
> I guess this has to be solved in the read_raster_runif function

As long as `raster()` on the GeoTIFF (within `read_raster_runif()`) does not correctly return the correct WKT (while it should, because it's OK in the file), then reassigning the CRS is certainly needed indeed - and more generally it is an approach that protects against future upstream bugs and changes anyway.

However, here we needed a check of the CRS included in the file itself, which `raster()` cannot currently do (see issue), nor could `gdalUtils` on your machine, it seems. I hope it will work on your machine with `rgdal` in #58, which IMO is better than using `gdalUtils` (`gdalUtils` maintenance seems to have stalled since Feb 2020). Also, the `gdalUtils` result needed manual post-processing because of the different output format.

**Comment by florisvdh** [comment]
FYI the [raster issue](https://github.com/rspatial/raster/issues/199) has been solved in the dev version of `raster`. So checking the GeoTIFF WKT can once again be done directly on the raster object obtained from the GeoTIFF. But if my `rgdal` approach (PR #58) works for you @ToonHub, then you don't need to bother using `raster`'s dev version.

```r
> filepath <-  file.path(fileman_up("n2khab_data"), "10_raw/raster_runif/raster_runif.tif")
> r <- raster(filepath)
> wkt(r) == sf::st_crs(31370)$wkt
[1] TRUE
```

```
─ Packages ─────────────────────────────────────────────────────────────────────────
 package * version date       lib source                          
 raster  * 3.4-9   2021-05-03 [1] Github (rspatial/raster@17a5ac3)
```

**Comment by ToonHub** [comment]
- [x] add hashes to googlesheet with n2khab data sources
- [x] copy result to Q-drive

**Pull request merged**
